### PR TITLE
fixes #259 allowing trailing Z for all variants of time parts

### LINKED ISSUE #259: Timestamp 2010-01-01T00:00Z throws Date or DateTime Format not supported
**Describe the bug**
Trying to use the timestamp 2010-01-01T00:00Z as a start timestamp for the oshdb-api throws an 
```java
..
.timestamps("2010-01-01T00:00Z", "2020-01-01-T:00:00Z")
.count();
```
[main] ERROR org.heigit.bigspatialdata.oshdb.api.mapreducer.MapReducer - unable to parse ISO date string: Date or DateTime Format not supported: 2010-01-01T00:00Z

### PR DESCRIPTION
**Pull request by mcauer**
# Changes proposed in this pull request:
## Type of change
Please delete if not relevant:
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Description
- Extending the ISODateTimeParser to allow a trailing Z for all variants of time parts in a DateTime String. e.g. 2020-05-01T15Z
- 
-

## Corresponding issue
Closes #259 

## New or changed dependencies:
-

# Checklist
- [ ] My code follows the [code-style](https://github.com/GIScience/oshdb/blob/master/CONTRIBUTING.md) rules and I have checked on the [static analyses](https://jenkins.ohsome.org/job/oshdb/view/change-requests/) and [benchmark](https://reports.ohsome.org/oshdb-benchmarks/) (if applicable) results
- [x] I have commented my code
- [x] I have written javadoc (required for public methods)
- [x] I have added sufficient unit tests
- [x] I have made corresponding changes to the [documentation](https://github.com/GIScience/oshdb/tree/master/documentation)
- [x] I have updated the [CHANGELOG.md](https://github.com/GIScience/oshdb/blob/master/CHANGELOG.md)
- [x] I have adjusted the [examples](https://gitlab.gistools.geog.uni-heidelberg.de/giscience/big-data/ohsome/oshdb-examples) and [benchmark](https://reports.ohsome.org/oshdb-benchmarks/) if necessary

### CODE REVIEW

File: oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/time/ISODateTimeParser.java [hunk 1]
```diff
@@ -31,60 +31,58 @@
...
-   * @throws Exception
+   * @throws Exception if Date or Date-Time pattern is not supported
    */
-  public static ZonedDateTime parseISODateTime(String isoDateTimeString) throws Exception{
+  public static ZonedDateTime parseISODateTime(String isoDateTimeString) throws Exception {
     ZonedDateTime zdt = null;
+
+    // always remove trailing Z, no other timezones are allowed anyways
+    if (isoDateTimeString.endsWith("Z")) {
+      isoDateTimeString = isoDateTimeString.substring(0,isoDateTimeString.length() - 1);
```
Comment (tyrasd) [inline oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/time/ISODateTimeParser.java:41]: minor: missing whitespace at: `…(0,isoDate…`

File: oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/time/ISODateTimeParser.java [hunk 2]
```diff
@@ -31,60 +31,58 @@
...
    * @param isoDateTimeString ISO Date or ISO DateTime string
    * @return ZonedDateTime
-   * @throws Exception
+   * @throws Exception if Date or Date-Time pattern is not supported
    */
-  public static ZonedDateTime parseISODateTime(String isoDateTimeString) throws Exception{
+  public static ZonedDateTime parseISODateTime(String isoDateTimeString) throws Exception {
     ZonedDateTime zdt = null;
+
+    // always remove trailing Z, no other timezones are allowed anyways
```
Comment (tyrasd) [inline oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/time/ISODateTimeParser.java:39]: maybe "not allowed" is the wrong wording here: in a few places we actually [do](https://github.com/GIScience/oshdb/blob/0.5.9/oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/time/ISODateTimeParser.java#L20) [claim](https://docs.ohsome.org/ohsome-api/v1/time.html) [to](https://github.com/GIScience/oshdb/blob/master/documentation/manual/filters.md#timestamps) "support ISO 8601" timestamps. So, right now, the fact that currently only UTC strings are parsed is "just" a matter of us not bothering to implement these parts of the ISO standard. :wink: 

I see two possibilities now:
1. Document better that we only support a subset of the ISO standard, and explicitly define which one.
2. Embrace that the current implementation is still incomplete, but be open to have the code be extended further in the future (this might be done by switching to a different date-time parser library for full ISO support – I heard [Joda Time](https://www.joda.org/joda-time/) should be quite good).

File: oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/time/ISODateTimeParser.java [hunk 3]
```diff
@@ -31,60 +31,58 @@
...
-      break;
-    case 24:
-      // pattern = "uuuu-MM-DDTHH:MM:ss.sssZ";
-      zdt = ZonedDateTime.parse(isoDateTimeString, DateTimeFormatter.ISO_DATE_TIME);
-      break;
-    default:
-      throw new Exception("Date or DateTime Format not supported: " + isoDateTimeString);
+      case 4:
+        // pattern = "uuuu";
+        zdt = Year.parse(isoDateTimeString).atDay(1).atStartOfDay(ZoneId.of("Z"));
```
Comment (tyrasd) [inline oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/time/ISODateTimeParser.java:49]: it could make sense to store `ZoneId.of("Z")` in a constant, because it is needed in each one of the swtich-cases here… maybe it is just a matter of taste, though

**Review by tyrasd — COMMENTED** [review]
found some mostly minor issues here, and would be glad to hear what you think about our level of ISO standard compliance. :blush:

**Comment by tyrasd** [comment]
ah, @mcauer – it seems like you did not yet add the email `michael.auer@heigit.org` to your github account, which you used to sign off the commits (66a1926c702bc8f10d940cd3e42ead3156e19e08 and aa4f7806b3120c32919901ec4de2287d2c3a0de4). Because of this the commits are not detected to belong to you.

Also, it would be superb if you could perhaps set up signing of your git commits using gpg: https://docs.github.com/en/github/authenticating-to-github/signing-commits :smiley:

File: oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/time/ISODateTimeParser.java (hunk 2 above)
Comment (mcauer) [reply oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/time/ISODateTimeParser.java:39]: Extending the support for more timezones would result in a breaking change, because all query definitions without Z at the end would change their meaning and would/should be interpreted as local time. But which local time? The servers local time, but it should be interpreted as the users local time.
I think this would be a big source of errors. 
I would prefer a better documentation that we only support UTC and leave it to applications and users to convert local dates if they need them for some reasons.

**Comment by mcauer** [comment]
> ah, @mcauer – it seems like you did not yet add the email `michael.auer@heigit.org` to your github account, which you used to sign off the commits ([66a1926](https://github.com/GIScience/oshdb/commit/66a1926c702bc8f10d940cd3e42ead3156e19e08) and [aa4f780](https://github.com/GIScience/oshdb/commit/aa4f7806b3120c32919901ec4de2287d2c3a0de4)). Because of this the commits are not detected to belong to you.
> 
> Also, it would be superb if you could perhaps set up signing of your git commits using gpg: https://docs.github.com/en/github/authenticating-to-github/signing-commits smiley

@tyrasd thanks for pointing me on it. Added my email and created a gpg key for future commits.

File: oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/time/ISODateTimeParser.java (hunk 2 above)
Comment (tyrasd) [reply oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/time/ISODateTimeParser.java:40]: ok, that makes sense. so, let's start by documenting this in the javadoc above (https://github.com/GIScience/oshdb/blob/0.5.9/oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/time/ISODateTimeParser.java#L20)?

**Comment by tyrasd** [comment]
>  created a gpg key for future commits

looks like it is not yet working 100%, since https://github.com/GIScience/oshdb/pull/265/commits/4eb0dc6a18f0124d4964ba0b5b40f900e9a34380 seems to be unsigned, AFAICs. :wink:

File: oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/time/ISODateTimeParser.java (hunk 2 above)
Comment (mcauer) [reply oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/time/ISODateTimeParser.java:43]: Ok. Improved JavaDoc in this commit [4eb0dc6](https://github.com/GIScience/oshdb/pull/265/commits/4eb0dc6a18f0124d4964ba0b5b40f900e9a34380)

Comment (mcauer) [reply oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/time/ISODateTimeParser.java:43]: I think it's also important to document more precisely in the ohsome-API.

Comment (tyrasd) [reply oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/time/ISODateTimeParser.java:43]: great, I've now also updated the oshdb documentation in this branch: https://github.com/GIScience/oshdb/blob/fix-issue-259-timestamp-formats/documentation/manual/filters.md#timestamps (https://github.com/GIScience/oshdb/pull/265/commits/ce15ccdd238e5e771e40261a81b1b0adc0794495)

**Comment by mcauer** [comment]
> > created a gpg key for future commits
> 
> looks like it is not yet working 100% correctly on your side, since [4eb0dc6](https://github.com/GIScience/oshdb/commit/4eb0dc6a18f0124d4964ba0b5b40f900e9a34380) seems to be unsigned, AFAICs. wink

I used IntelliJ UI to commit. Can this be configured in IntelliJ?

File: oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/time/ISODateTimeParser.java (hunk 2 above)
Comment (tyrasd) [reply oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/time/ISODateTimeParser.java:43]: > I think it's also important to document more precisely in the ohsome-API.

yep -> I've opened https://github.com/GIScience/ohsome-api/issues/48 for that.

**Comment by mcauer** [comment]
> > > created a gpg key for future commits
> > 
> > 
> > looks like it is not yet working 100% correctly on your side, since [4eb0dc6](https://github.com/GIScience/oshdb/commit/4eb0dc6a18f0124d4964ba0b5b40f900e9a34380) seems to be unsigned, AFAICs. wink
> 
> I used IntelliJ UI to commit. Can this be configured in IntelliJ?

Ok now it worked. puh. :)

**Comment by tyrasd** [comment]
:+1: 

a few unit tests for the class would be nice, if you don't mind…

**Comment by mcauer** [comment]
> +1
> 
> a few unit tests for the class would be nice, if you don't mind…

ok, still working on that.

File: oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/time/ISODateTimeParser.java [hunk 4]
```diff
@@ -18,8 +18,11 @@
 
   /**
    * Converts an ISO 8601 Date or combined Date-Time String into a UTC based ZonedDateTime Object.
+   * <br>
```
Comment (tyrasd) [inline oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/time/ISODateTimeParser.java:21]: would it be better to use `<p>` here, since these should semantically be different paragraphs, right?

File: oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/time/ISODateTimeParser.java [hunk 5]
```diff
@@ -40,6 +43,16 @@
   public static ZonedDateTime parseISODateTime(String isoDateTimeString) throws Exception {
     ZonedDateTime zdt = null;
 
+    isoDateTimeString = isoDateTimeString.trim();
+
+    if (isoDateTimeString.startsWith("-")) {
+      throw new Exception("Negative Dates are not supported: " + isoDateTimeString);
```
Comment (tyrasd) [inline oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/time/ISODateTimeParser.java:49]: can we maybe get rid of the generic `Exception` class here? I know this is quite a bit off-topic from the initial pull request goal (to fix #259), but adding new cases of such "bad code" is not great either.

Comment (rtroilo) [reply oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/time/ISODateTimeParser.java:49]: Hey @tyrasd , can you explain why this is "bad code"? And do we have a guideline or should write one which defines such cases as "bad code" with suggestions for "good code".

Comment (tyrasd) [reply oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/time/ISODateTimeParser.java:49]: well, maybe "bad code" was not the best wording. But sonarlint classifies this as _code smell_ with _major severity_: https://rules.sonarsource.com/java/RSPEC-112

> Using such generic exceptions as Error, RuntimeException, Throwable, and Exception prevents calling methods from handling true, system-generated exceptions differently than application-generated errors. See also http://cwe.mitre.org/data/definitions/397.html and https://wiki.sei.cmu.edu/confluence/display/java/ERR07-J.+Do+not+throw+RuntimeException%2C+Exception%2C+or+Throwable

Comment (rtroilo) [reply oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/time/ISODateTimeParser.java:49]: What kind of suggestion should we do here.
We could use a already existing exception like:

1. java.time.format.DateTimeParseException

Comment (tyrasd) [reply oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/time/ISODateTimeParser.java:49]: IMO option 3 (defining our own exception like ISODateTimeParserException) or 2 would be better in this instance because this here is a specific exception of the choices we made in the OSHDB here. But option 1 would still be better than the generic `Exception` class.

Comment (mcauer) [reply oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/time/ISODateTimeParser.java:49]: Hi, I leave it up to you to choose a "well smelling" Exception flavor. That's not my expertise. So I would be glad if someone else takes over the exception handling. Functionally the issue is fixed so far and the class is much safer to use as before and well tested. So feel free to assign someone else for the exceptions.

Comment (tyrasd) [reply oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/time/ISODateTimeParser.java:49]: thanks, I will take care of the rest :+1:

File: oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/time/IsoDateTimeParserTest.java [hunk 6]
```diff
@@ -0,0 +1,175 @@
...
+        Assert.assertEquals(yyyy_mm_dd_hh_mm_ss[0], parseIsoDateTime(yyyy_mm_dd_hh_mm_ss[1]).toString());
+        Assert.assertEquals(yyyy_mm_dd_hh_mm_ssz[0], parseIsoDateTime(yyyy_mm_dd_hh_mm_ssz[1]).toString());
+
+        Assert.assertEquals(yyyy_mm_dd_hh_mm_ss_sss[0], parseIsoDateTime(yyyy_mm_dd_hh_mm_ss_sss[1]).toString());
+        Assert.assertEquals(yyyy_mm_dd_hh_mm_ss_sssz[0], parseIsoDateTime(yyyy_mm_dd_hh_mm_ss_sssz[1]).toString());
+
+    }
+
+
+    @Test(expected = Exception.class)
```
Comment (joker234) [inline oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/time/IsoDateTimeParserTest.java:63]: Is a generic `Exception` sufficient here and in the following tests?

File: oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/time/IsoDateTimeParserTest.java [hunk 7]
```diff
@@ -0,0 +1,175 @@
...
+    public void throwsWrongDateParseISODateTime() throws Exception {
+        //Wrong Date
+        String wrongDateTime = "2020-13-01T00:00";
+        parseIsoDateTime(wrongDateTime);
+    }
+
+
+    @Test
+    public void testParseISOPeriod() throws Exception {
```
Comment (joker234) [inline oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/time/IsoDateTimeParserTest.java:123]:
```suggestion
    public void testParseIsoPeriod() throws Exception {
```

File: oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/time/IsoDateTimeParserTest.java [hunk 8]
```diff
@@ -0,0 +1,175 @@
...
+import java.time.Period;
+import java.util.Map;
+
+import static org.heigit.bigspatialdata.oshdb.util.time.IsoDateTimeParser.parseIsoDateTime;
+import static org.heigit.bigspatialdata.oshdb.util.time.IsoDateTimeParser.parseIsoPeriod;
+
+public class IsoDateTimeParserTest {
+
+    @Test
+    public void testParseISODateTime() throws Exception {
```
Comment (joker234) [inline oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/time/IsoDateTimeParserTest.java:16]:
```suggestion
    public void testParseIsoDateTime() throws Exception {
```

File: oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/time/IsoDateTimeParserTest.java [hunk 9]
```diff
@@ -0,0 +1,175 @@
...
+        Assert.assertEquals(yyyy_mm_dd_hh_mm_ssz[0], parseIsoDateTime(yyyy_mm_dd_hh_mm_ssz[1]).toString());
+
+        Assert.assertEquals(yyyy_mm_dd_hh_mm_ss_sss[0], parseIsoDateTime(yyyy_mm_dd_hh_mm_ss_sss[1]).toString());
+        Assert.assertEquals(yyyy_mm_dd_hh_mm_ss_sssz[0], parseIsoDateTime(yyyy_mm_dd_hh_mm_ss_sssz[1]).toString());
+
+    }
+
+
+    @Test(expected = Exception.class)
+    public void throwsNegativeDateParseISODateTime() throws Exception {
```
Comment (joker234) [inline oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/time/IsoDateTimeParserTest.java:64]:
```suggestion
    public void throwsNegativeDateParseIsoDateTime() throws Exception {
```

File: oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/time/IsoDateTimeParserTest.java [hunk 10]
```diff
@@ -0,0 +1,175 @@
...
+        //Negative Dates
+        String nyyyy = "-0333";
+        parseIsoDateTime(nyyyy);
+    }
+
+    @Test(expected = Exception.class)
+    public void throwsShortYearParseISODateTime() throws Exception {
```
Comment (joker234) [inline oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/time/IsoDateTimeParserTest.java:71]:
```suggestion
    public void throwsShortYearParseIsoDateTime() throws Exception {
```

File: oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/time/IsoDateTimeParserTest.java [hunk 11]
```diff
@@ -0,0 +1,175 @@
...
+        //Short Year
+        String yy = "12";
+        parseIsoDateTime(yy);
+    }
+
+    @Test(expected = Exception.class)
+    public void throwsPosTimezoneHHParseISODateTime() throws Exception {
```
Comment (joker234) [inline oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/time/IsoDateTimeParserTest.java:78]:
```suggestion
    public void throwsPosTimezoneHHParseIsoDateTime() throws Exception {
```

File: oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/time/IsoDateTimeParserTest.java [hunk 12]
```diff
@@ -0,0 +1,175 @@
...
+        String posTimezone_hh = "2020-02-17T23:55+02";
+        parseIsoDateTime(posTimezone_hh);
+    }
+
+    @Test(expected = Exception.class)
+    public void throwsPosTimezoneHHMMParseISODateTime() throws Exception {
```
Comment (joker234) [inline oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/time/IsoDateTimeParserTest.java:84]:
```suggestion
    public void throwsPosTimezoneHHMMParseIsoDateTime() throws Exception {
```

File: oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/time/IsoDateTimeParserTest.java [hunk 13]
```diff
@@ -0,0 +1,175 @@
...
+        String posTimezone_hhmm = "2020-02-17T23:55+0230";
+        parseIsoDateTime(posTimezone_hhmm);
+    }
+
+    @Test(expected = Exception.class)
+    public void throwsPosTimezoneHH_MMParseISODateTime() throws Exception {
```
Comment (joker234) [inline oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/time/IsoDateTimeParserTest.java:90]:
```suggestion
    public void throwsPosTimezoneHH_MMParseIsoDateTime() throws Exception {
```

File: oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/time/IsoDateTimeParserTest.java [hunk 14]
```diff
@@ -0,0 +1,175 @@
...
+        String posTimezone_hh_mm = "2020-02-17T23:55+02:30";
+        parseIsoDateTime(posTimezone_hh_mm);
+    }
+
+    //
+    @Test(expected = Exception.class)
+    public void throwsNegTimezoneHHParseISODateTime() throws Exception {
```
Comment (joker234) [inline oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/time/IsoDateTimeParserTest.java:97]:
```suggestion
    public void throwsNegTimezoneHHParseIsoDateTime() throws Exception {
```

File: oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/time/IsoDateTimeParserTest.java [hunk 15]
```diff
@@ -0,0 +1,175 @@
...
+        String negTimezone_hh = "2020-02-17T23:55-02";
+        parseIsoDateTime(negTimezone_hh);
+    }
+
+    @Test(expected = Exception.class)
+    public void throwsNegTimezoneHHMMParseISODateTime() throws Exception {
```
Comment (joker234) [inline oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/time/IsoDateTimeParserTest.java:103]:
```suggestion
    public void throwsNegTimezoneHHMMParseIsoDateTime() throws Exception {
```

File: oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/time/IsoDateTimeParserTest.java [hunk 16]
```diff
@@ -0,0 +1,175 @@
...
+        String negTimezone_hhmm = "2020-02-17T23:55-0230";
+        parseIsoDateTime(negTimezone_hhmm);
+    }
+
+    @Test(expected = Exception.class)
+    public void throwsNegTimezoneHH_MMParseISODateTime() throws Exception {
```
Comment (joker234) [inline oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/time/IsoDateTimeParserTest.java:109]:
```suggestion
    public void throwsNegTimezoneHH_MMParseIsoDateTime() throws Exception {
```

File: oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/time/IsoDateTimeParserTest.java [hunk 17]
```diff
@@ -0,0 +1,175 @@
...
+        String negTimezone_hh_mm = "2020-02-17T23:55-02:30";
+        parseIsoDateTime(negTimezone_hh_mm);
+    }
+
+    @Test(expected = Exception.class)
+    public void throwsWrongDateParseISODateTime() throws Exception {
```
Comment (joker234) [inline oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/time/IsoDateTimeParserTest.java:115]:
```suggestion
    public void throwsWrongDateParseIsoDateTime() throws Exception {
```

File: oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/time/IsoDateTimeParserTest.java [hunk 18]
```diff
@@ -0,0 +1,175 @@
...
+        Map<String, Object> twoWeeks = parseIsoPeriod(weekPeriod);
+        Period twoWeeksPeriod = (Period) twoWeeks.get("period");
+        Duration twoWeeksDuration = (Duration) twoWeeks.get("duration");
+        Assert.assertEquals(14, twoWeeksPeriod.getDays());
+        Assert.assertTrue(twoWeeksDuration.isZero());
+
+    }
+
+    @Test(expected = Exception.class)
+    public void throwsFormatParseISOPeriod() throws Exception {
```
Comment (joker234) [inline oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/time/IsoDateTimeParserTest.java:164]:
```suggestion
    public void throwsFormatParseIsoPeriod() throws Exception {
```

File: oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/time/IsoDateTimeParserTest.java [hunk 19]
```diff
@@ -0,0 +1,175 @@
...
+        // test throw exeption for unsupported formats
+        parseIsoPeriod("PT1Y2M");
+    }
+
+    @Test(expected = Exception.class)
+    public void throwsZeroLengthParseISOPeriod() throws Exception {
```
Comment (joker234) [inline oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/time/IsoDateTimeParserTest.java:170]:
```suggestion
    public void throwsZeroLengthParseIsoPeriod() throws Exception {
```

File: oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/time/IsoDateTimeParser.java [hunk 20]
```diff
@@ -0,0 +1,187 @@
...
+   *  ISO Date Period: P2W (weeks)
+   *  ISO Time Duration: PT1H (hours)
+   *  ISO Time Duration: PT30M (minutes)
+   *  ISO Time Duration: PT20S (seconds)
+   *  combined DateTime: P1Y3M5DT5H30M20S
+   * </pre>
+   *
+   * @param isoPeriodString ISO Period string
+   * @return HashMap with a Period object and a Duration object
+   * @throws OSHDBTimeoutException if the ISOPeriod string is not valid
```
Comment (joker234) [inline oshdb-util/src/main/java/org/heigit/bigspatialdata/oshdb/util/time/IsoDateTimeParser.java:123]:
```suggestion
   * @throws OSHDBTimeoutException if the isoPeriodString is not valid
```

**Review by joker234 — CHANGES_REQUESTED** [review]
I think some tests with valid ISO 8601 timestrings but with a not supported timezone (non-UTC) are missing. And the Changelog is missing!

File: oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/time/IsoDateTimeParserTest.java (hunk 6 above)
Comment (tyrasd) [reply oshdb-util/src/test/java/org/heigit/bigspatialdata/oshdb/util/time/IsoDateTimeParserTest.java]: made it more rigorous in 497792f28d14f7d992d9ba732362c6f23a545e00

**Comment by tyrasd** [comment]
> I think some tests with valid ISO 8601 timestrings but with a not supported timezone (non-UTC) are missing.

@joker234 isn't that already there with tests like `throwsPosTimezoneHHParseIsoDateTime` (etc.) [here](https://github.com/GIScience/oshdb/pull/265/files#diff-d48583837a4ad76758f220734ad2eff7bd1e0c9c81aa95f27efe4994d3169edaR78-R113)? Or do you mean something else?

**Comment by tyrasd** [comment]
> And the Changelog is missing!

done

**Comment by joker234** [comment]
> > I think some tests with valid ISO 8601 timestrings but with a not supported timezone (non-UTC) are missing.
> 
> @joker234 isn't that already there with tests like `throwsPosTimezoneHHParseIsoDateTime` (etc.) [here](https://github.com/GIScience/oshdb/pull/265/files#diff-d48583837a4ad76758f220734ad2eff7bd1e0c9c81aa95f27efe4994d3169edaR78-R113)? Or do you mean something else?

Nevermind, that's alright.

**Review by joker234 — APPROVED** [review]
