### PR TITLE
Bugfix/#286 closed channel exception

### LINKED ISSUE #286: java.nio.channels.ClosedChannelException
On Ubuntu 18.04, running ETL with the usual command line:

mvn exec:java -Dexec.mainClass="org.heigit.bigspatialdata.oshdb.tool.importer.extract.Extract" -Dexec.args="--pbf /home/ertert/oshdb-new/oshdb-tool/etl/files/switzerland-internal.osh.pbf -tmpDir ./tmpFiles -workDir ./results --timevalidity_from 2017-01-01" -Dexec.cleanupDaemonThreads=false

when execution starts I get:

joining on thread Thread[org.heigit.bigspatialdata.oshdb.tool.importer.extract.Extract.main(),5,org.heigit.bigspatialdata.oshdb.tool.importer.extract.Extract]
extracting key tables ...[WARNING] 
java.lang.RuntimeException: java.nio.channels.ClosedChannelException

which becomes :

BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.887 s
[INFO] Finished at: 2020-11-26T08:24:50Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default-cli) on project etl: An exception occured while executing the Java class. java.nio.channels.ClosedChannelException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default-cli) on project etl: An exception occured while executing the Java class. java.nio.channels.ClosedChannelException

java.nio.channels.ClosedChannelException is a fairly common issue and generally related to programming. Any thoughts?

### PR DESCRIPTION
**Pull request by rtroilo**
This PR closes Issue #286.

### Description
Revert some code refactoring, 5e8ba71d218888d7dc2b79513013383b7473466a which leads to eagerly closed streams!

### Corresponding issue
Closes #286

### CODE REVIEW

File: oshdb-tool/oshpbf-parser/src/main/java/org/heigit/bigspatialdata/oshpbf/parser/rx/RxOshPbfReader.java [hunk 1]
```diff
@@ -142,59 +142,57 @@ private static boolean seekStartPos(RandomAccessFile raf, long pos, long limit)
...
+      } else {
+        for (int i = 0; i < 3; i++) {
+          pushBackBytes[i] = pushBackBytes[i + 1];
+        }
+        pushBackBytes[3] = (byte) nextByte;
       }
-  
-      // we reach the end of stream and found no signature
-      return -1;
+
```
Comment (joker234) [inline oshdb-tool/oshpbf-parser/src/main/java/org/heigit/bigspatialdata/oshpbf/parser/rx/RxOshPbfReader.java:190]:
```suggestion

```

File: oshdb-tool/oshpbf-parser/src/main/java/org/heigit/bigspatialdata/oshpbf/parser/rx/RxOshPbfReader.java [hunk 2]
```diff
@@ -142,59 +142,57 @@ private static boolean seekStartPos(RandomAccessFile raf, long pos, long limit)
...
       }
-  
-      // we reach the end of stream and found no signature
-      return -1;
+    
+      nextByte = pushBackStream.read();
+      totalBytesRead++;
     }
+// we reach the end of stream and found no signature
+    return -1;
```
Comment (joker234) [inline oshdb-tool/oshpbf-parser/src/main/java/org/heigit/bigspatialdata/oshpbf/parser/rx/RxOshPbfReader.java:195]:
```suggestion
    // we reach the end of stream and found no signature
    return -1;
```

**Review by joker234 — CHANGES_REQUESTED** [review]
Two minor indention issues. Apart from that :+1:

**Review by joker234 — APPROVED** [review]
