### PR TITLE
make ohsome filters work with groupByEntity queries

### LINKED ISSUE #321: ohsome filters don't work with groupByEntity queries
**Describe the bug**
`filter(String)` does not work together with `groupByEntity`

**To Reproduce**

```java
Number osmTypeFilterResult = mapreducer.groupByEntity().osmType(OSMType.WAY).count();
Number stringFilterResult = mapreducer.groupByEntity().filter("type:way").count();

assertEquals(osmTypeFilterResult, stringFilterResult);
```

**Expected behavior**
The two queries above should both produce the same result.

**Error messages, logs, screenshots**
```
java.lang.ClassCastException
Caused by: java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class org.heigit.ohsome.oshdb.api.object.OSMEntitySnapshot
```

**Affected versions:**
 - OSHDB Version 0.6.0
 - OSHDB Version 0.7.0-SNAPSHOT (current master branch)

### PR DESCRIPTION
**Pull request by tyrasd**
For now this just contains a failing unit test to showcase the problem. After this is resolved, we should create patch release `0.6.1` together with #326 (which needs to be backported in `0.5.11` as well).

# Changes proposed in this pull request:
## Type of change
Please delete if not relevant:
- [x] Bug fix (non-breaking change which fixes an issue)

## Corresponding issue
Closes #321

# Checklist
- [x] My code follows the [code-style](https://github.com/GIScience/oshdb/blob/master/CONTRIBUTING.md) rules and I have checked on the [static analyses](https://jenkins.ohsome.org/job/oshdb/view/change-requests/) and [benchmark](https://reports.ohsome.org/oshdb-benchmarks/) (if applicable) results
- [x] I have commented my code
- [x] I have written javadoc (required for public methods)
- [x] I have added sufficient unit tests
- ~~I have made corresponding changes to the [documentation](https://github.com/GIScience/oshdb/tree/master/documentation)~~
- [x] I have updated the [CHANGELOG.md](https://github.com/GIScience/oshdb/blob/master/CHANGELOG.md)
- ~~I have adjusted the [examples](https://gitlab.gistools.geog.uni-heidelberg.de/giscience/big-data/ohsome/oshdb-examples) and [benchmark](https://reports.ohsome.org/oshdb-benchmarks/) if necessary~~

### CODE REVIEW

File: oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/MapReducer.java [hunk 1]
```diff
@@ -754,20 +755,41 @@ protected MapReducer(MapReducer<?> obj) {
...
-    } else if (ret.forClass.equals(OSMEntitySnapshot.class)) {
-      ret = ret.filter(x -> {
-        OSMEntitySnapshot s = (OSMEntitySnapshot) x;
-        return f.applyOSMGeometry(s.getEntity(), s::getGeometry);
-      });
+    if (this.grouping == Grouping.BY_ID) {
+      if (ret.forClass.equals(OSMContribution.class)) {
+        @SuppressWarnings("unchecked") MapReducer<X> result = (MapReducer<X>)
+            ret.map(x -> (Collection<OSMContribution>) x)
+                .map(contributions -> Collections2.filter(contributions, c -> c != null
```
Comment (tyrasd) [inline oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/MapReducer.java:762]: todo: check if it's save to assume that this is still a `List` (not just a generic `Collection` which doesn't implement stuff like `get(index)`

File: oshdb-api/src/test/java/org/heigit/ohsome/oshdb/api/tests/TestOhsomeFilter.java [hunk 2]
```diff
@@ -57,8 +57,7 @@ public void testFilterString() throws Exception {
 
   @Test
   public void testFilterObject() throws Exception {
-    MapReducer<OSMEntitySnapshot> mr = createMapReducer();
-    Number result = mr
+    Number result = createMapReducer()
```
Comment (joker234) [inline oshdb-api/src/test/java/org/heigit/ohsome/oshdb/api/tests/TestOhsomeFilter.java:60]: Is this a cleanup that changes or affects anything apart from syntax cleanup?

File: oshdb-api/src/test/java/org/heigit/ohsome/oshdb/api/tests/TestOhsomeFilter.java [hunk 3]
```diff
@@ -79,12 +78,20 @@ public void testAggregateFilter() throws Exception {
...
         .filter(filterParser.parse("(geometry:polygon or geometry:other) and building=*"))
         .count();
 
     assertEquals(42, result.get(OSMType.WAY).intValue());
   }
+
+  @Test
+  public void testFilterGroupByEntity() throws Exception {
+    MapReducer<OSMEntitySnapshot> mr = createMapReducer();
+    Number osmTypeFilterResult = mr.groupByEntity().osmType(OSMType.WAY).count();
```
Comment (joker234) [inline oshdb-api/src/test/java/org/heigit/ohsome/oshdb/api/tests/TestOhsomeFilter.java:92]: `osmType(…)` is deprecated. What would be the plan for this test, if the method is removed in the future? Maybe add a comment to this test explaining what needs to be done if this method is removed.

File: oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/MapReducer.java [hunk 4]
```diff
@@ -754,17 +754,44 @@ protected MapReducer(MapReducer<?> obj) {
...
-        return f.applyOSMGeometry(s.getEntity(), s::getGeometry);
-      });
+    if (this.grouping == Grouping.NONE) {
+      // no grouping -> directly filter using the geometries of the snapshot / contribution
+      if (ret.forClass.equals(OSMEntitySnapshot.class)) {
+        ret = ret.filter(x -> {
+          OSMEntitySnapshot s = (OSMEntitySnapshot) x;
+          return f.applyOSMGeometry(s.getEntity(), s::getGeometry);
+        });
+      } else if (ret.forClass.equals(OSMContribution.class)) {
```
Comment (joker234) [inline oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/MapReducer.java:764]: not covered by any tests

File: oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/MapReducer.java [hunk 5]
```diff
@@ -754,17 +754,44 @@ protected MapReducer(MapReducer<?> obj) {
...
+      // grouping by entity -> filter each list entry individually
+      if (ret.forClass.equals(OSMEntitySnapshot.class)) {
+        @SuppressWarnings("unchecked") MapReducer<X> filteredListMapper = (MapReducer<X>)
+            ret.map(x -> (Collection<OSMEntitySnapshot>) x)
+                .map(snapshots -> snapshots.stream().filter(s ->
+                    s != null && f.applyOSMGeometry(s.getEntity(), s::getGeometry))
+                    .collect(Collectors.toCollection(ArrayList::new)))
+                .filter(snapshots -> !snapshots.isEmpty());
+        ret = filteredListMapper;
+      } else if (ret.forClass.equals(OSMContribution.class)) {
```
Comment (joker234) [inline oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/MapReducer.java:781]: not covered by any tests

File: oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/MapReducer.java [hunk 6]
```diff
@@ -754,17 +754,44 @@ protected MapReducer(MapReducer<?> obj) {
...
+                .map(contributions -> contributions.stream()
+                    .filter(c -> c != null
+                        && (f.applyOSMGeometry(c.getEntityBefore(), c::getGeometryBefore)
+                        || f.applyOSMGeometry(c.getEntityAfter(), c::getGeometryAfter)))
+                    .collect(Collectors.toCollection(ArrayList::new)))
+                .filter(contributions -> !contributions.isEmpty());
+        ret = filteredListMapper;
+      }
+    } else {
+      throw new UnsupportedOperationException(
```
Comment (joker234) [inline oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/MapReducer.java:793]: Is this an Exception that can actually happen? I think no, so I suppose you cannot test it. But we should keep it, if someone extends the `Grouping` enum without adding a case here.

**Review by joker234 — COMMENTED** [review]
First remarks. I'll have a look in the new contents of `else if (this.grouping == Grouping.BY_ID)` later.

File: oshdb-api/src/test/java/org/heigit/ohsome/oshdb/api/tests/TestOhsomeFilter.java (hunk 2 above)
Comment (tyrasd) [reply oshdb-api/src/test/java/org/heigit/ohsome/oshdb/api/tests/TestOhsomeFilter.java:60]: just a minor cleanup, when the test only needs one mapreducer, we don't need the local variable. :shrug:

File: oshdb-api/src/test/java/org/heigit/ohsome/oshdb/api/tests/TestOhsomeFilter.java (hunk 3 above)
Comment (tyrasd) [reply oshdb-api/src/test/java/org/heigit/ohsome/oshdb/api/tests/TestOhsomeFilter.java:92]: right. that would be one of the todos in #324

File: oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/MapReducer.java (hunk 4 above)
Comment (tyrasd) [reply oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/MapReducer.java:764]: huh, true. Strictly speaking this part of the code wasn't really changed in this PR. but I guess it would be good to have some basic test for this path as well.

File: oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/MapReducer.java (hunk 6 above)
Comment (tyrasd) [reply oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/MapReducer.java:793]: no, it can't happen at the moment because the enum only has two possibilities. At first, I had implemented this with a `switch` (with `default` to be the same as `case NONE`), but then sonarlint complained that one shouldn't use switch statements with only two branches :shrug: I thought by adding the "hypothetical" throw statement here, it's clear that something must be added if at some point there would be an additional _grouping_ possibility.

File: oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/MapReducer.java (hunk 4 above)
Comment (tyrasd) [reply oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/MapReducer.java:765]: oh gosh, this branch was actually pretty buggy and slipped through because it wasn't covered by the tests. :see_no_evil: thanks for spotting that!

should be fixed in d468552e

**Comment by joker234** [comment]
Additional remark: Should we rename `TestOhsomeFilter.java` to `TestOSHDBFilter.java`?

File: oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/MapReducer.java (hunk 5 above)
Comment (tyrasd) [reply oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/MapReducer.java:788]: fixed in d468552

**Comment by tyrasd** [comment]
> Additional remark: Should we rename `TestOhsomeFilter.java` to `TestOSHDBFilter.java`?

sure, that wouldn't hurt. :arrow_right: 170cc32f

File: oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/MapReducer.java (hunk 6 above)
Comment (joker234) [reply oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/MapReducer.java:807]: So let's keep that in mind for future versions of the oshdb :+1:

File: oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/MapReducer.java [hunk 7]
```diff
@@ -754,17 +755,57 @@ protected MapReducer(MapReducer<?> obj) {
...
+      } else if (ret.forClass.equals(OSMContribution.class)) {
+        ret = ret.filter(x -> {
+          OSMContribution c = (OSMContribution) x;
+          if (c.is(ContributionType.CREATION)) {
+            return f.applyOSMGeometry(c.getEntityAfter(), c::getGeometryAfter);
+          } else if (c.is(ContributionType.DELETION)) {
+            return f.applyOSMGeometry(c.getEntityBefore(), c::getGeometryBefore);
+          } else {
+            return f.applyOSMGeometry(c.getEntityBefore(), c::getGeometryBefore)
+                || f.applyOSMGeometry(c.getEntityAfter(), c::getGeometryAfter);
```
Comment (joker234) [inline oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/MapReducer.java:774]: According to my local tests, the lines 770 to 774 are still not tested. They look sane to me, so I wouldn't require it, but maybe it makes sense to do that anyway.

File: oshdb-api/src/test/java/org/heigit/ohsome/oshdb/api/tests/TestOSHDBFilter.java [hunk 8]
```diff
@@ -33,21 +35,34 @@
...
+  private MapReducer<OSMEntitySnapshot> createMapReducerOSMEntitySnapshot() throws Exception {
     return OSMEntitySnapshotView.on(oshdb)
         .areaOfInterest(bbox)
         .timestamps("2014-01-01");
   }
 
+  private MapReducer<OSMContribution> createMapReducerOSMContribution() throws Exception {
+    return OSMContributionView.on(oshdb)
+        .areaOfInterest(bbox)
+        .timestamps("2008-01-01", "2014-01-01");
```
Comment (joker234) [inline oshdb-api/src/test/java/org/heigit/ohsome/oshdb/api/tests/TestOSHDBFilter.java:53]: With this time range, I suppose the idea is that `createMapReducerOSMContribution()` contains the same result as `createMapReducerOSMEntitySnapshot()`. I think that's okay for now since the contribution endpoint is tested properly in other oshdb-api tests, correct?

File: oshdb-api/src/test/java/org/heigit/ohsome/oshdb/api/tests/TestOSHDBFilter.java [hunk 9]
```diff
@@ -79,12 +93,26 @@ public void testAggregateFilter() throws Exception {
...
+    SortedMap<OSMType, Integer> result = createMapReducerOSMEntitySnapshot()
         .aggregateBy(x -> x.getEntity().getType())
         .filter(filterParser.parse("(geometry:polygon or geometry:other) and building=*"))
         .count();
 
     assertEquals(42, result.get(OSMType.WAY).intValue());
   }
+
+  @Test
+  public void testFilterGroupByEntity() throws Exception {
```
Comment (joker234) [inline oshdb-api/src/test/java/org/heigit/ohsome/oshdb/api/tests/TestOSHDBFilter.java:105]: Could be split in two separate tests. If it would contain more than the two asserts, SonarLint would recommend that, but I think it's okay for now.

**Review by joker234 — APPROVED** [review]
Some minor comments and suggestions. None of them needs to be addressed necessarily to merge this PR.

File: oshdb-api/src/test/java/org/heigit/ohsome/oshdb/api/tests/TestOSHDBFilter.java (hunk 8 above)
Comment (tyrasd) [reply oshdb-api/src/test/java/org/heigit/ohsome/oshdb/api/tests/TestOSHDBFilter.java:53]: yes, that was the idea. since there are no matching-but-later-deleted elements in this test data set, the results should match.

File: oshdb-api/src/test/java/org/heigit/ohsome/oshdb/api/tests/TestOSHDBFilter.java (hunk 9 above)
Comment (tyrasd) [reply oshdb-api/src/test/java/org/heigit/ohsome/oshdb/api/tests/TestOSHDBFilter.java:105]: sure, but I think this is good enough for now ;)

File: oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/MapReducer.java (hunk 7 above)
Comment (tyrasd) [reply oshdb-api/src/main/java/org/heigit/ohsome/oshdb/api/mapreducer/MapReducer.java:774]: if we had a properly crafted test data set, it would be easy to trigger these branches as well. That would be nice to have eventually. But I think we can live with the current implementation for now, right?
