### PR TITLE
fix crash when relation references redacted way

### LINKED ISSUE #325: race condition when redacted deleted way is referenced by relations
**Describe the bug**
When a relation (like [`relation/10215810`](https://www.openstreetmap.org/api/0.6/relation/10215810/history)) references a way which has only one "deleted" version after redactions (like [`way/687863323`](https://www.openstreetmap.org/api/0.6/way/687863323/history)), the CellIterator hits a race condition [here](https://github.com/GIScience/oshdb/blob/0.5.10/oshdb/src/main/java/org/heigit/bigspatialdata/oshdb/osh/OSHEntities.java#L459).

**To Reproduce**

```java
    OSMEntitySnapshotView
          .on(oshdb).keytables(keytables)
          .areaOfInterest(new OSHDBBoundingBox(44.0,46.0,44.5,46.5))
          .timestamps("2020-12-01")
          .osmType(OSMType.RELATION)
          .osmEntityFilter(e -> e.getId() == 10215810L)
          .count();
```

alternatively triggered via ohsome API:
```bash
curl -X GET "https://api.ohsome.org/v1/elements/count?bboxes=44.0%2C46.0%2C44.5%2C46.5&filter=type%3Arelation%20and%20id%3A10215810&format=json&time=2014-01-01%2F2020-01-01%2FP1Y"
```

**Expected behavior**
no error should be triggered

**Error messages, logs, screenshots**

```
java.util.NoSuchElementException
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1000)
	at org.heigit.bigspatialdata.oshdb.osh.OSHEntities._getModificationTimestamps(OSHEntities.java:459)
	at org.heigit.bigspatialdata.oshdb.osh.OSHEntities.getModificationTimestamps(OSHEntities.java:312)
	at org.heigit.bigspatialdata.oshdb.osh.OSHEntities.getModificationTimestamps(OSHEntities.java:246)
	at org.heigit.bigspatialdata.oshdb.util.celliterator.CellIterator.lambda$iterateByContribution$7(CellIterator.java:485)
```

**System (please complete the following information):**
 - OSHDB Version: `0.7.0-SNAPSHOT`, `0.6.0`, `0.5.10`

**Additional context**
We should probably provide a backport for this bug fix for 0.6 and 0.5.

### PR DESCRIPTION
**Pull request by tyrasd**
fixes #325

# Changes proposed in this pull request:
## Type of change
Please delete if not relevant:
- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist
- [x] My code follows the [code-style](https://github.com/GIScience/oshdb/blob/master/CONTRIBUTING.md) rules and I have checked on the [static analyses](https://jenkins.ohsome.org/job/oshdb/view/change-requests/) and [benchmark](https://reports.ohsome.org/oshdb-benchmarks/) (if applicable) results
- [x] I have commented my code
- I have written javadoc (required for public methods) :arrow_right:  #327
- [x] I have added sufficient unit tests
- ~~I have made corresponding changes to the [documentation](https://github.com/GIScience/oshdb/tree/master/documentation)~~
- [x] I have updated the [CHANGELOG.md](https://github.com/GIScience/oshdb/blob/master/CHANGELOG.md)
- ~~I have adjusted the [examples](https://gitlab.gistools.geog.uni-heidelberg.de/giscience/big-data/ohsome/oshdb-examples) and [benchmark](https://reports.ohsome.org/oshdb-benchmarks/) if necessary~~

### CODE REVIEW

File: oshdb/src/test/java/org/heigit/ohsome/oshdb/osh/OSHRelationTest.java [hunk 1]
```diff
@@ -258,4 +258,34 @@ public void testToString() throws IOException {
...
+    OSHNode hnode1 = OSHNodeImpl.build(new ArrayList<>(List.of(
+        new OSMNode(123L, 2, new OSHDBTimestamp(2L), 2L, 0, new int[]{}, 0, 0),
+        new OSMNode(123L, 1, new OSHDBTimestamp(1L), 1L, 0, new int[]{}, 0, 0))));
+    OSHNode hnode2 = OSHNodeImpl.build(new ArrayList<>(List.of(
+        new OSMNode(124L, 2, new OSHDBTimestamp(2L), 2L, 0, new int[]{}, 0, 0),
+        new OSMNode(124L, 1, new OSHDBTimestamp(1L), 1L, 0, new int[]{}, 0, 0))));
+
+    OSHWay hway1 = OSHWayImpl.build(new ArrayList<>(List.of(
+        new OSMWay(1, 1, new OSHDBTimestamp(1L), 1L, 0, new int[]{}, new OSMMember[]{
+            new OSMMember(123, OSMType.NODE, 0),
```
Comment (joker234) [inline oshdb/src/test/java/org/heigit/ohsome/oshdb/osh/OSHRelationTest.java:272]: I think it's not an issue, but you use `123` here and `123L` above. The same syntax would look a little bit nicer. Same in the next line.

File: oshdb/src/test/java/org/heigit/ohsome/oshdb/osh/OSHRelationTest.java [hunk 2]
```diff
@@ -258,4 +258,34 @@ public void testToString() throws IOException {
     assertEquals(expResult, result);
   }
 
+  @Test
```
Comment (joker234) [inline oshdb/src/test/java/org/heigit/ohsome/oshdb/osh/OSHRelationTest.java:261]: add comment as description, e.g. link to #325

**Review by joker234 — APPROVED** [review]
just a few suggestions :+1:
